"""users table

Revision ID: 023784ee7f14
Revises: 
Create Date: 2020-05-28 17:39:51.000744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023784ee7f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clay_name'), 'clay', ['name'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('clay_id_1', sa.Integer(), nullable=True),
    sa.Column('clay_id_2', sa.Integer(), nullable=True),
    sa.Column('picture', sa.BINARY(), nullable=True),
    sa.ForeignKeyConstraint(['clay_id_1'], ['clay.id'], ),
    sa.ForeignKeyConstraint(['clay_id_2'], ['clay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_clay_name'), table_name='clay')
    op.drop_table('clay')
    # ### end Alembic commands ###
