"""empty message

Revision ID: 0d9ca895cb83
Revises: 7718868ba4ab
Create Date: 2020-06-09 22:38:28.002106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ca895cb83'
down_revision = '7718868ba4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clay', 'user', ['user_id'], ['id'])
    op.add_column('glaze', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('glaze', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('glaze', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_glaze_create_date'), 'glaze', ['create_date'], unique=False)
    op.create_index(op.f('ix_glaze_delete_date'), 'glaze', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'glaze', 'user', ['user_id'], ['id'])
    op.add_column('item', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_create_date'), 'item', ['create_date'], unique=False)
    op.create_index(op.f('ix_item_delete_date'), 'item', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_delete_date'), table_name='item')
    op.drop_index(op.f('ix_item_create_date'), table_name='item')
    op.drop_column('item', 'user_id')
    op.drop_column('item', 'delete_date')
    op.drop_column('item', 'create_date')
    op.drop_constraint(None, 'glaze', type_='foreignkey')
    op.drop_index(op.f('ix_glaze_delete_date'), table_name='glaze')
    op.drop_index(op.f('ix_glaze_create_date'), table_name='glaze')
    op.drop_column('glaze', 'user_id')
    op.drop_column('glaze', 'delete_date')
    op.drop_column('glaze', 'create_date')
    op.drop_constraint(None, 'clay', type_='foreignkey')
    # ### end Alembic commands ###
