"""empty message

Revision ID: 497f673e534f
Revises: 
Create Date: 2020-06-04 13:49:01.556982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f673e534f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_glaze_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'item__glaze', ['item_glaze_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'item_glaze_id')
    # ### end Alembic commands ###
