"""users table

Revision ID: 6050b2d61c7f
Revises: 
Create Date: 2020-05-29 23:41:23.999987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6050b2d61c7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('clay_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('glaze_id_1', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('glaze_id_2', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('image_name', sa.String(length=256), nullable=True))
    op.add_column('item', sa.Column('surface_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'clay', ['clay_id'], ['id'])
    op.create_foreign_key(None, 'item', 'glaze', ['glaze_id_2'], ['id'])
    op.create_foreign_key(None, 'item', 'glaze', ['glaze_id_1'], ['id'])
    op.create_foreign_key(None, 'item', 'surface', ['surface_id'], ['id'])
    op.drop_column('item', 'picture')
    op.drop_column('item', 'clay_id_2')
    op.drop_column('item', 'clay_id_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('clay_id_1', sa.INTEGER(), nullable=True))
    op.add_column('item', sa.Column('clay_id_2', sa.INTEGER(), nullable=True))
    op.add_column('item', sa.Column('picture', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'clay', ['clay_id_1'], ['id'])
    op.create_foreign_key(None, 'item', 'clay', ['clay_id_2'], ['id'])
    op.drop_column('item', 'surface_id')
    op.drop_column('item', 'image_name')
    op.drop_column('item', 'glaze_id_2')
    op.drop_column('item', 'glaze_id_1')
    op.drop_column('item', 'clay_id')
    # ### end Alembic commands ###
