"""empty message

Revision ID: 6c10b408d77a
Revises: 497f673e534f
Create Date: 2020-06-04 14:07:17.389392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c10b408d77a'
down_revision = '497f673e534f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_glaze',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('glaze_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item__glaze')
    op.drop_column('item', 'item_glaze_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_glaze_id', sa.INTEGER(), nullable=True))
    op.create_table('item__glaze',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('glaze_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_glaze')
    # ### end Alembic commands ###
