"""empty message

Revision ID: 7718868ba4ab
Revises: c96eea85225d
Create Date: 2020-06-09 22:36:29.384655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7718868ba4ab'
down_revision = 'c96eea85225d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clay', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('clay', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('clay', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clay_create_date'), 'clay', ['create_date'], unique=False)
    op.create_index(op.f('ix_clay_delete_date'), 'clay', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'clay', 'user', ['user_id'], ['id'])
    op.add_column('glaze', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('glaze', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('glaze', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_glaze_create_date'), 'glaze', ['create_date'], unique=False)
    op.create_index(op.f('ix_glaze_delete_date'), 'glaze', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'glaze', 'user', ['user_id'], ['id'])
    op.add_column('item', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_create_date'), 'item', ['create_date'], unique=False)
    op.create_index(op.f('ix_item_delete_date'), 'item', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    op.add_column('surface', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('surface', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.add_column('surface', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_surface_create_date'), 'surface', ['create_date'], unique=False)
    op.create_index(op.f('ix_surface_delete_date'), 'surface', ['delete_date'], unique=False)
    op.create_foreign_key(None, 'surface', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surface', type_='foreignkey')
    op.drop_index(op.f('ix_surface_delete_date'), table_name='surface')
    op.drop_index(op.f('ix_surface_create_date'), table_name='surface')
    op.drop_column('surface', 'user_id')
    op.drop_column('surface', 'delete_date')
    op.drop_column('surface', 'create_date')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_delete_date'), table_name='item')
    op.drop_index(op.f('ix_item_create_date'), table_name='item')
    op.drop_column('item', 'user_id')
    op.drop_column('item', 'delete_date')
    op.drop_column('item', 'create_date')
    op.drop_constraint(None, 'glaze', type_='foreignkey')
    op.drop_index(op.f('ix_glaze_delete_date'), table_name='glaze')
    op.drop_index(op.f('ix_glaze_create_date'), table_name='glaze')
    op.drop_column('glaze', 'user_id')
    op.drop_column('glaze', 'delete_date')
    op.drop_column('glaze', 'create_date')
    op.drop_constraint(None, 'clay', type_='foreignkey')
    op.drop_index(op.f('ix_clay_delete_date'), table_name='clay')
    op.drop_index(op.f('ix_clay_create_date'), table_name='clay')
    op.drop_column('clay', 'user_id')
    op.drop_column('clay', 'delete_date')
    op.drop_column('clay', 'create_date')
    # ### end Alembic commands ###
