"""picture

Revision ID: e36202bd471f
Revises: 023784ee7f14
Create Date: 2020-05-28 19:20:46.395436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36202bd471f'
down_revision = '023784ee7f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('picture', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###
